package com.example.orthoj.Model.Enumeration;

public enum TypeQLAnamEnfant {
    STRUCTURE_FAMILIALE,
    DYNAMIQUE_FAMILIALE,
    ANTECEDENTS_FAMILIAUX,
    CONDITIONS_NATALES,
    DEVELOPPEMENT_PSYCHOMOTEURS,
    DEVELOPPEMENT_LANGAGIER,
    CARACTERE_COMPORTEMENT
}
